---
- hosts: localhost
  become: yes
  become_user: root
  connection: local
  roles:
    - base 
    - { role: developer, when: "ansible_hostname in ['wroman']" }

#     - { role: resilio, when: "ansible_distribution_version == '16.04'" } 
