#!/bin/bash

user=`who -q | grep -v "^#" | head -1`

if [ -z "$user" ]; then
    echo "No user logged in. Aborting" >&2
    exit 1
fi

if [ "$1" = "-u" ]; then
    changes=$(git pull | grep 'Already up-to-date')
    if [ -z "$changes" ]; then
        echo "No changes, borting" >&2
        exit 1
    fi
fi

if [ `whoami` = 'root' ]; then
	ansible-playbook laptop.yml
else
	ansible-playbook -K laptop.yml
fi
